apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure/cert-manager
  - ../../infrastructure/authentik
  # ArgoCD managed manually - self-management causes loops
