---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  encryptedData:
    client-id: AgCygxKrUajalElS90XIt4YuNkyl2IaD5kZ8wUr2XKcspsINCpfJTGYt8sfIrsuIbhnBRBUAzKqXD5ZEH+qBvswLcwRraMySeAn+E7Hb/K8So0CU0m8mqwhuPxW0yC2kkh86musGnQGaA6M02NcE9QLb9DFW/iiwQtYFXZKbweyHtUkyDTOFdAhB6qNE8KAJznlHKO9wkF6pOe0hJzjZkEZNHJWMowCAMGyB8JEJaTZUHpJY3mT2NeQsvfogxluIAcMUlw00qfQvHmDhmWjIfiLAZH/1G9qD2lhj2OK2GmPapePpmMjvGZyqsHF6LJaRb9xDmIph+Pu3CYlSp5ygAzFvOlb2vlHBFUGranWRMe0sh+uh49QZgYlTMW1UM5ckB1iAbqtexOEJSEBunRD0MAfcFjoZfPqbtFX7AE8DASzKHqSH4+rBoOjQVoUIuRQdZMr6a1AESvgABh2HFCtHxUz0whEUS0E+ibkwDB+hKvw2mwx3V2LmDxjG1/NchlKDN6Qp/czWM78YsOyhkBXqJvp5LEIjfFOKygQMiETHa7ZjbrJ4h9gujKC7lGUl/ywbLgRVrvtWwTLObwfGFp3ZmX78kGj3ulzHyC7vA6OUrhyjSUh7kMcITuhzOrrvqrB/ggw0C+Bn4l5O3yHweFXbNqvZS8hx8a6onmFzltmcvdho38SPzjfQnTCcgisY0N9+nFYBGTzNIWBa
    client-secret: AgC3YlFKwqhGBodV7gGj7Yp7op9SC7ooo5804sMI51/BesoHULWGDW7dG7TEbjfuJJLJ+KEUmu69eInzU+Da2X1GCumtcgd/caHUwGpQeMoY2bVtQ8R3vSCvcr2tNq3rqtdEXQwSoZSp47ZY8yOGJ8BKy+2SRe6NpCkqIga4LOO1nWJwts6TvooHSB6xepnkGjbxujSeOjNDvjuKtgUGCjg5Oj3QfDA6hfU5XDCqc3JBIqdHtXFb9GjtR7SGDv+LPtYC5isWUAocz/n/UrUwEge+z5k6FH7kUEahAt0m2qSNGmcJv/7qJ7/cMWHFTmOyGKir8TUNqy8VRS6acH+hzRj1lK4q1eUoV/iZUG+qgVBLMKSSfnR+QIT8ieFXhPKQcBLQr0epR9cqQg6ijwGQ7xohwiTp/d/L7V0kJ8xM1d3a36HG5jmJB507+QVHKhrgnglFFST64xlex8nI3Iy0Tt9q/ESoK5R4HhVfqayj1n/qBdeOwjtNMQ0S2t1Rl9Ag9pqVlrMZg4TINqZNBchKiHYIm6gGmxKVl9HafVIOnM7cjJQ7AfMoOIAwoR7sR7QOCckdf/fl04s+H2eIkIS1yjgVqrv1xZKxIibrkLK5ngmTPC0+V0LbA8mPyWn8/loTKIcXjZcYuyXANer2bPlqt5lLGddh/tSYsHfWE+0p+Vk4UC4SZj+lY8uPIXJRgJOp/jVTzB0xEzTBQuJ8urU2OzAGmt5S+im8tw+q8zmJx7YMMslNEIAhaMo+PYqVDU8W7Sf4S+9TltU2Zokn5u224B2Q7jUisn9wvDKZXMS4bqgzUZtaXmOMX1fLv+sB8IW8rdLm+X2qDVaC30uEqXbMIgw80MibNgLhox+TwfDtNF09bw==
  template:
    metadata:
      name: grafana-oidc-secret
      namespace: monitoring
    type: Opaque
