apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runner
resources:
  - namespace.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: homelab
    includeSelectors: false
