apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-helm.yaml
  - authelia.yaml
  - cert-manager.yaml
  - cert-manager-helm.yaml
  - cloudflare-tunnel.yaml
  - external-dns.yaml
  - minio.yaml
  - open-webui.yaml
  - outline.yaml
  - sealed-secrets.yaml
