apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actions-runner-controller.yaml
  - actions-runner-infra.yaml
  - alertmanager.yaml
  - authentik.yaml
  - cert-manager.yaml
  - cloudnative-pg.yaml
  - external-dns.yaml
  - longhorn.yaml
  - plane.yaml
  - plane-extras.yaml
  - telnet-server.yaml
  - loki.yaml
  - nfs-proxy.yaml
  - open-webui.yaml
