apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager.yaml
  - authentik.yaml
  - cert-manager.yaml
  - cloudnative-pg.yaml
  - external-dns.yaml
  - longhorn.yaml
  - plane.yaml
  - plane-extras.yaml
  - telnet-server.yaml
  - loki.yaml
