apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - sealed-secret.yaml
  - sealed-pull-secret.yaml
  - minio-sealed-secret.yaml
  - litestream-config.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - pdb.yaml
