apiVersion: v1
kind: Service
metadata:
  name: campfire
  namespace: campfire
  labels:
    app.kubernetes.io/name: campfire
    app.kubernetes.io/component: chat
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    app.kubernetes.io/name: campfire
  ports:
    - port: 80
      targetPort: http
      name: http
