apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocketbase
  namespace: pocketbase
  labels:
    app.kubernetes.io/name: pocketbase
    app.kubernetes.io/component: ingress
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: authentik-ak-outpost-forward-auth-outpost@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - pb.lab.axiomlayer.com
      secretName: pocketbase-tls
  rules:
    - host: pb.lab.axiomlayer.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pocketbase
                port:
                  number: 8090
