apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare-tunnel
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/part-of: homelab
data:
  config.yaml: |
    tunnel: homelab
    credentials-file: /etc/cloudflared/creds/credentials.json
    no-autoupdate: true
    ingress:
      - hostname: argocd.lab.axiomlayer.com
        service: http://argocd-server.argocd.svc:80
      - hostname: auth.lab.axiomlayer.com
        service: http://authelia.authelia.svc:9091
      - hostname: ai.lab.axiomlayer.com
        service: http://open-webui.open-webui.svc:8080
      - hostname: docs.lab.axiomlayer.com
        service: http://outline.outline.svc:3000
      - service: http_status:404
