apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - sealed-secret.yaml
  - postgres-cluster.yaml
  - blueprints-configmap.yaml
  - rbac.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/part-of: homelab
    includeSelectors: false
