apiVersion: apps/v1
kind: Deployment
metadata:
  name: telnet-server
  namespace: telnet-server
  labels:
    app: telnet-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telnet-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: telnet-server
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9000'
    spec:
      containers:
      - name: telnet-server
        image: ghcr.io/jasencarroll/telnet-server:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 1Mi
          limits:
            cpu: 500m
            memory: 100Mi
        ports:
        - containerPort: 2323
          name: telnet
        - containerPort: 9000
          name: metrics
