apiVersion: v1
kind: Service
metadata:
  name: telnet-server
  namespace: telnet-server
  labels:
    app: telnet-server
spec:
  type: LoadBalancer
  ports:
  - port: 2323
    name: telnet
    protocol: TCP
    targetPort: 2323
  selector:
    app: telnet-server
---
apiVersion: v1
kind: Service
metadata:
  name: telnet-server-metrics
  namespace: telnet-server
  labels:
    app: telnet-server
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9000'
spec:
  type: ClusterIP
  ports:
  - port: 9000
    name: metrics
    protocol: TCP
    targetPort: 9000
  selector:
    app: telnet-server
