apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-10.2.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/version: "12.3.0"
    app.kubernetes.io/managed-by: argocd
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth]
    disable_login_form = false
    oauth_auto_login = false
    [auth.generic_oauth]
    enabled = true
    name = Authentik
    allow_sign_up = true
    use_pkce = true
    scopes = openid email profile groups
    auth_url = https://auth.lab.axiomlayer.com/application/o/authorize/
    token_url = https://auth.lab.axiomlayer.com/application/o/token/
    api_url = https://auth.lab.axiomlayer.com/application/o/userinfo
    client_id = $__env{client-id}
    client_secret = $__env{client-secret}
    email_attribute_path = email
    login_attribute_path = preferred_username
    name_attribute_path = name
    role_attribute_path = contains(groups[*], 'Homelab Admins') && 'Admin' || 'Viewer'
    skip_org_role_sync = false
    use_refresh_token = true
    id_token_attribute_name = id_token
    allow_assign_grafana_admin = true
    empty_scopes = false
    [database]
    type = postgres
    host = grafana-db-rw.monitoring.svc:5432
    name = grafana
    user = grafana
    password = $__env{GF_DATABASE_PASSWORD}
    ssl_mode = disable
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    root_url = https://grafana.lab.axiomlayer.com
    [session]
    provider = postgres
    provider_config = user=grafana password=$__env{GF_DATABASE_PASSWORD} host=grafana-db-rw.monitoring.svc port=5432 dbname=grafana sslmode=disable
    [users]
    auto_assign_org_role = Viewer
