apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana-certificate.yaml
  - grafana-oidc-sealed-secret.yaml
  - grafana-db-cluster.yaml
  - grafana-db-networkpolicy.yaml
  - grafana-configmap.yaml
