apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
  namespace: {{APP_NAME}}
  labels:
    app.kubernetes.io/name: {{APP_NAME}}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  ports:
    - port: {{PORT}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{APP_NAME}}
