apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-proxy
  namespace: nfs-proxy
  labels:
    app.kubernetes.io/name: nfs-proxy
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nfs-proxy
        app.kubernetes.io/component: server
    spec:
      nodeSelector:
        kubernetes.io/hostname: neko
      containers:
        - name: nfs-server
          image: erichough/nfs-server@sha256:1efd4ece380c5ba27479417585224ef857006daa46ab84560a28c1224bc71e9e
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
            - name: nfs-udp
              containerPort: 2049
              protocol: UDP
            - name: mountd
              containerPort: 20048
              protocol: TCP
            - name: rpcbind
              containerPort: 111
              protocol: TCP
            - name: statd
              containerPort: 32765
              protocol: TCP
            - name: statd-udp
              containerPort: 32765
              protocol: UDP
            - name: lockd
              containerPort: 32767
              protocol: TCP
            - name: lockd-udp
              containerPort: 32767
              protocol: UDP
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          env:
            - name: NFS_EXPORT_0
              value: "/data/k8s-backup *(rw,sync,no_subtree_check,no_root_squash,fsid=0)"
            - name: NFS_LOG_LEVEL
              value: "DEBUG"
          volumeMounts:
            - name: upstream-nfs
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: upstream-nfs
          nfs:
            server: 192.168.1.234
            path: /volume/e8e70d24-82e0-45f1-8ef6-f8ca399ad2d6/.srv/.unifi-drive/Shared_Drive_Example/.data
