apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-tls
  namespace: alertmanager
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: alertmanager-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - alerts.lab.axiomlayer.com
