apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealed-secret.yaml
  - applications/argocd-helm.yaml
  - applications/authelia.yaml
  - applications/cert-manager.yaml
  - applications/cert-manager-helm.yaml
  - applications/cloudflare-tunnel.yaml
  - applications/external-dns.yaml
  - applications/minio.yaml
  - applications/open-webui.yaml
  - applications/outline.yaml
  - applications/sealed-secrets.yaml
