apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificate.yaml
  - ingress.yaml
  - configmaps.yaml
  - sealed-secret.yaml
  - applications/cert-manager.yaml
  - applications/authentik.yaml
  - applications/cloudnative-pg.yaml
  - applications/telnet-server.yaml
  - applications/loki.yaml
  - applications/kube-prometheus-stack.yaml
